name: AutoBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v4.2.2
    - name: Set up JDK 21
      uses: actions/setup-java@v4.7.1
      with:
        java-version: '8'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4.4.1

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build Mods
      run: ./gradlew build
      env:
        GITHUB_RUN_NUMBER: ${{ github.run_number }}

    - name: Upload Files
      uses: actions/upload-artifact@v4.6.2
      with:
        name: Ore-Stages-Actions-${{ github.run_number }}
        path: build/libs/*.jar